google_play:
  id: de.stamplab
  path_to_service_account_json: /home/timbastin/Schreibtisch/l3montree/stats-exporter/service_account.json
  cloud_storage_bucket: pubsite_prod_8729964373865066144

db: 
  user: exporter
  password: secret
  database_name: exporter
  host: 127.0.0.1
  port: 3306