google_play:
  id: com.app
  path_to_service_account_json: /path/to/service_account.json
  cloud_storage_bucket: pubsite_prod_xxxxxx

db: 
  user: exporter
  password: secret
  database_name: exporter
  host: 127.0.0.1
  port: 3306
