version: "3.3"
services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: exporter
      MYSQL_USER: exporter
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db-data:/var/lib/mysql

volumes:
  mysql-db-data:
  postgresql-db-data:
